<?php $title = "About The Game";
$desc = "Learn about the world of Enthysia and it's three main inhabitants; the Taaskians, Loyios, and Nethians. The setting and characters of sideQUEST are rich in history and contribute to the overall atmosphere of the game.";
include ('top.php'); ?>
            
            <h2>About</h2>
            <p>The web game "sideQUEST" combines the nostalgia of 8-bit, NES style role playing experiences with the exciting concept of gamification. Your quest is to save the world of Enthysia from the ominous darkness that is slowly turning the inhabitants into idle shells. In order to progress through the game, you too must save yourself from idleness: various real-world tasks are added as you advance, and by completing them and updating your status through a mobile device you open up new areas of the "sideQUEST" world. The people of Enthysia are counting on you, and the only way to save the world is to believe in yourself; or just your ability to take out the trash.</p>
            <p>The world of Enthysia is inhabited by three different races, the Taaskians, the Loyios, and the Nethians. It is a mainly continental world split up into three sectors; the Taaskian colonized lands near the south, the unclaimed and dangerous areas towards the middle, and the mysterious and mainly uninhabited northern regions of the Nethians. The land is rich with forests and open plains, as well as various mountainous and beach areas. The climate is naturally warm and breezy, with the smaller, island sections more sunny and humid while the northern regions are wind torn and cold, accompanied by a larger period of nighttime.</p>
            <h4>The Inhabitants</h4> 
            <img src="images/characters/pro.png" style="float:left; padding:0px 10px 5px 0px;" alt="" />
            <p>The <b>Taaskian</b> race are the newest inhabitants of Enthysia, travelling from a far off, unknown land to colonize this unexplored area. In the short time they have been in Enthysia, however, they have become the most abundant of the three main races. That is the result of the peoples overall energetic attitudes and vigorous spirit, allowing them to colonize and evolve at an exponential rate. While they still only inhabit roughly half of the lands, they have become the main citizens of Enthysia.</p>
            <p>The protagonist of "sideQUEST" is from the Taaskian race, a young man from the south-most village who was mysteriously visited by a Nethian and bestowed with a three-pointed star mark on his forehead, announced as the hero of an ancient prophecy who would save the world from the darkness.</p>
            <img src="images/characters/loyios.png" style="float:right; padding:0px 0px 5px 10px;" alt="" />
            <p>The <b>Loyios</b> race is a brutish, goblin-like group of creatures that lived on Enthysia before the Taaskians migrated. They used to roam the land freely, living mainly in stone huts and canvas tents, until the colonization of the Taaskians had depleted thier numbers and forced them into the less desired areas of Enthysia. They are lazy and sullen creatures, however the takeover of their homelands by the Taaskians seems to have forced them to amass and scheme to retake the area, causing some to wonder if the darkness is their doing.</p>
            <img src="images/characters/nethian.png" style="float:left; padding:0px 10px 5px 0px;" alt="" />
            <p>Little is known of the <b>Nethian</b> race, only that they have lived in Enthysia for a long time, maybe longer than the Loyios. While witnessing one is extremely uncommon, they have been described as spirit-like creatures with long grey hair, black skin, and wearing ragged cloaks with jeweled pommels. They mainly reside in the uninhabited areas to the north, where the climate and environment is too dangerous and unpredictable to allow for normal residents.</p>
            <p>Since the darkness originated from the north, many have thought that it was caused by the Nethians, though none can explain why. This theory has been discredited since one Nethian unexpectedly travelled far south to seek the help of a Taaskian who was supposedly the chosen one and destined to save the world.</p>
            
<?php include ('bottom.php') ?>