					<div class="expand">
                    <h4 style="color:#700003;">Vision Statement</h4>
						<div class="handbook">
                        <p>"sideQUEST" is designed like a classic role playing game where you, as the protagonist, have to travel across an amazing and mysterious world and search for a way to save its inhabitants from a darkness that is corrupting the land with poisonous idleness. No one knows where the darkness has come from, but those unlucky enough to be engulfed by its shroud have become idle, unhelpful, and careless. The entire world is in peril of this danger unless an upcoming hero (that's you!) can inspire the remaining masses and battle the monstrosities lurking in the darkness in order to remove its hostile spell from the land.</p>
						<p>The game play revolves around two main objectives; to explore the world and battle enemies like in a traditional RPG-style environment, as well as to motivate those inhabitants not affected by the environment with your good deeds and self-worth. Unlike in traditional RPGs, however, you do not advance through the game by moving a joystick, but by completing various external tasks that you record into the game using an input device, such as a mobile phone. Advancement is rewarded when these various tasks are completed, and while the in-game leader board of tasks adds up the inhabitants take notice, and use your example to better themselves and fight off the oncoming dangers of the darkness.</p>
                    	</div>
                    </div>
                    <div class="expand">
					<h4 style="color:#700003;">Storyline</h4>
                    	<div class="handbook">
                        <p>The world of Enthysia is inhabited by three races; the Taaskians, a newer race of human-like creatures whose energetic attitudes has allowed them to advance as a species exponentially over the past century, the Loyios, a race of goblin-like creatures who used to roam the lands freely until the Taaskians began their structured evolution, forcing the lazy race out of their homes and into the less-desired sections of Enthysia, and the Nethians, mysterious spirit creatures that have resided in the land long before even the Loyios but have become increasingly uncommon since the Tasskian expansion. The drive of the Taaskians has allowed them to prosper, "taking" the land from the Loyios, who hate them for it and appear to have begun amassing and scheming to retake control of their homelands. However, the horizon holds more dangers than the jealous skirmishes of the races.</p>
                        <p>To the North, in the old, mainly uninhabited territories of the Nethians, darkness has begun to roll across the land. When the darkness covered the north-most of the Tasskian villages, the people there went through a terrible transformation. Their skin turned black and their hair grey. Their eyes sunk deep into their skulls and disappeared into a deep void. They became sluggish and unmotivated, and soon the once thriving village deteriorated and was consumed by the conveniently waiting Loyios. Being initially lazy themselves, the Loyios were mainly unaffected by the mysterious darkness.</p>
                        <p>Many blamed the Loyios for this danger, knowing how jealous they were of the Tasskian and their energetic advancement and the recent signs of their assembly. Others blamed the Nethians, as the darkness had originated from their old lands and was just as unknown as they were. However, no one had seen a Nethian in quite some time, and their existence had become more legend than fact. No matter who had created this danger, there was no doubt that it was coming, and no one knew what they could do to prevent it from engulfing them all.</p>
                        <p>Soon the darkness crept down the lands of Enthysia and enshrouded the Tasskian villages one by one. Soon even some of the Loyios encampments became affected, though the changes were lass apparent in and detrimental to the already languid race. While the Tasskians panicked and fled, the eager Loyios happily took over their villages as they were abandoned. The Tasskians migrated south as the darkness slowly swept over the land and turned those inhabitants unlucky enough to become caught in it into idle, gloomy shells of men. Enthysia became a world of chaos and destruction, every day another step towards a dark and foreboding end. Tasskian people begged their leaders, and their gods for those that believed, to spare them from this undesirable fate, but the darkness still flowed across the land unimpeded and swallowed everything in its path, making no designation as to which race it poisioned.</p>
                        <p>One day a Taaskian harbor village at the southernmost point of Enthysia had an unexpected visitor. An old Nethian slowly and solemnly sauntered through the village, the people too shocked by the first sight of one on over fifty years to raise the alarm of its coming. Before long it had entered a small cottage nearest to the sea and paused in front of the young man who was living there. The Nethian spoke, its voice unhurried and deep, but in a song-like language unknown to the Taaskian people. However it appeared that this man could understand what it was saying without pause, for as he listened he nodded and knelt in respect before the ancient creature when he had concluded his story. The Nethian placed a tendril-like arm upon the man's forehead, and then disappeared.</p>
                        <p>The man stood after this, and upon his forehead where the Nethian had touched him laid a black mark in the shape of a three pointed star. He told the people of the village that an ancient prophesy hidden in the north-most ruins of the Nethian lands of Enthysia named him as the one chosen to save the world from the darkness. The Nethian had given him wisdom that no other Tasskian could have or obtain about this world and the darkness. He pleaded that he would need the people to rally behind him on his quest, for while it takes one man to lead, it takes a thousand men to battle the darkness.</p>
                        </div>
                    </div>
                    <div class="expand">
                    <h4 style="color:#700003;">Gameplay</h4>
                    	<div class="handbook">
						<p>When the player first accesses "sideQUEST" on the web site, they must register. By creating a unique username and password the player will be able to save their progress as they advance in the game. Other than the username and password, the player must create a four letter nickname, which will be used to label the player after they have logged in both in-game and on the web site. Returning players must log in using their information in order to continue their game from the previous time they were on the web site. After logging in the player will have the option to log out at any time, however they will not be able to play once logged out.</p>
						<p>The beginning of sideQUEST brings the player to the start screen, where they have the option to either start a new game or, if they have played before, continue their old one. A new game places the player by the Taaskian village the protagonist inhabits (see Storyline), and is given an initial task to introduce them to the task system. If the player saved correctly during their last play of the game, then continuing a previous game will bring the player to the area of the Enthysia overworld they last saved at.</p>
						<p>"sideQUEST" operates mostly through information screens on both the web and mobile side of the game. On the web side, the map of Enthysia is split into slides, which the player can navigate by clicking four arrow buttons to each side of the display screen with the mouse. The arrow buttons become inaccessible when the player reaches an area of the map, usually by water or mountains, which they are unable to access. In addition, certain map slides contain further structures, such as towns and dungeon entrances, which can also be accessed by clicking on them and usually results in bringing the player to the new area. Players are encouraged to seek out possible access areas during their exploration of the vast regions of Enthysia to discover the different places and secrets the world contains.</p>
						<p>One of the main interactions the player can have with the world is the various Taaskian towns that are scattered across Enthysia. A normal village usually contains four structures; a shop, an inn, a temple, and a resident house. Most towns are accessible during the players first visit. As of now, the only real interactions can be had with the inn and the shop. The inn can be used to restore the players health by spending the night. The shop contains a group of randomly generated items that the player can take with them on their journey. In future development, a necessary task will be added to these areas to be used as payment for the services, which will be added and updated through an input mobile device (smart phone, tablet, etc). The payment sequence has yet to be designed.</p>
						<p>Another of the interactions possible with the main world is the dungeon entrances. Usually access to the dungeon is initially denied, removing the script that allows for the player to be able to click on the entrance, until they complete the assigned task added when in sight of the dungeon. Once the player has fulfilled the task and inputted it through their mobile device, they will then be able to click on the entrance, gaining access to the new area. Dungeon maps work very similarly to the over world navigation, though they are laid out in more of a maze-like structure. Stairs and treasure chests are some interactions that are unique to dungeons. Stairs take the player to other areas of the dungeon, which can lead to the final boss room or to a dead end. The treasure chest interactions have yet to be added, but will contain random items or have a small probability of containing enemies.</p>
						<p>While the player is travelling through the Enthysia over world or the many dungeons scattered across the land, they may come into contact with the enemy battle screen. Many of the other inhabitants of the world are hostile to the player, whether naturally or caused by the poison of the darkness. When confronted by an enemy, the player has the option of fighting or running. Running allows the player to escape without damage, with a small probability of failure, where upon the enemy will be able to attack for one turn. Once a run attempt is successful the player in returned to the map screen. If the player chooses the battle, they will engage in a turn based exchange of attacks, where the damage is determined by the attack and defense of the player and the enemy. Successful attacks deplete the combatants health points (HP), and when either of the combatants HP reaches 0, the battle is over. There is a small chance of either attack missing its target.</p>
						<p>If the player is the first to have their HP reach 0, the game ends, and they are returned to the start screen. There they may continue their game, but their position is returned to the initial village area. No other penalties are given. If the enemy is the first to have their HP reach 0, the player is rewarded with a set of experience points, or XP. When the player gain enough XP they gain a level, which increased their attack points (AP), defense points (DP), and HP. Leveling up is the main way for the player to become stronger, however once the item system has been implemented various weapons and armor can be bought at the shop or found in treasure chests to increase the stats of the player as well.</p>
						<p>Players will come across many different varieties of enemies in the world of Enthysia. The over world contains much of the same types; however each dungeon has a unique group of enemies in terms of appearance and stats. The player must be sure to visit the dungeons in the correct order; if they are not strong enough when they come into contact with enemies in certain dungeons, they could be in for a quick defeat. At the end of each dungeon the player will come in contact with the dungeon boss, a super powerful enemy designed in accordance to the dungeon. In addition to their increased stats, dungeon bosses usually have a unique power that can make the battle even more difficult. For example, the first boss has a change of raising his AP and DP for one turn of the battle. Make sure you are ready when you decide to face the boss.</p>
						<p>Some parts of the dungeons remain inaccessible to the player unless they complete certain tasks. When they reach certain areas, the task is added, and while the display might show the ability to travel in a certain direction, the arrow button disappears until the player has completed and inputted that task. The dungeon boss area is always locked until the player completes the necessary task. Once the task is completed and logged, the arrow will reappear, allowing access to the otherwise closed off area of the dungeon.</p>
						<p>In addition to dungeons and towns, there is another structure in the Enthysia over world that the player can access; the shrines and tunnels. Shires are scattered throughout the religious sectors of the Tasskian inhabited areas, which contain a temple and a set of stairs that lead to a path. This path usually takes the player to other sections of Enthysia that are initially blocked off by water or mountains. Tunnels are found in the atheistic area of Tasskian colonized lands, which work similarly to shires, except they do not contain temples. Shires and dungeons are usually locked off by a task, like with the dungeon entrances, which must be completed before access is granted.</p>
						<p>To the top left area of the display screen for web based gameplay is a fifth arrow button, pointing up. By clicking on this with the mouse, the player accesses the pause screen. In this screen the player can execute five different actions. "Continue" allows the player to exit the pause screen and return to the map screen to continue playing. "Quit" allows the player to exit their current game, bringing them back to the start screen. THIS DOES NOT SAVE THE PROGRESS. "Save" stores the player's current map area, stats, and inventory in a database for future access when they decide to stop playing at that time. "Items" shows the players current inventory (Not yet implemented). "Stats" shows the players current statistics, including HP, AP, DP, XP, time played, and tasks completed. The player’s level and nickname can be observed at any time during pause screen access.</p>
						<p>The stat for the number of tasks completed is important to advancement through the "sideQUEST" storyline. When the number increases, the overall Taaskian pride level grows, allowing more items to become available, certain procedures in Taaskian villages to become cheaper, and the people you interact with to become more helpful to your cause. Tasskian pride also opens up more areas for exploration, such as castles, high priest temples, and optional dungeons, in which you can find more powerful weapons, armor, and statistical advancements. A certain level of Taaskian pride must be reached before the player can access the final area and battle the darkness. While the completed tasks are currently calculated, Taaskian pride has yet to be implemented in the current port of the game.</p>
						<p>In addition to the display screen accessed on the web site, the second important interaction medium is through the mobile application. Players must have a phone that can access the internet and download apps in order to successfully play "sideQUEST". While there is not a fully functional app at this time, the link below the web display screen, when accessed through a mobile device, has been optimized to look and act like an app.</p>
						<p>The player is instructed by a pop up box in the display screen on the web site when a new task has been added. This display shows the name for the task in order for the player to connect it with the new list item on the app. Once a task has been added, the player can see it listed, among other unfinished tasks, on the mobile app. By pressing on the task, the player is given two type of information; a paragraph explaining what the task is for and a little bit of the history of Enthysia and its many mysterious areas in accordance to the storyline, as well as a button labeled "Submit". This button allows the player to submit the task to the game once it has been completed. When new tasks are added through the web side of the game, the app must be refreshed to properly display the task.</p>
						<p>As was mentioned above, once the new task had been added through the web side of the game, certain areas in the game become inaccessible. For example, when the player enters the map slide where the first dungeon entrance is located, they display pops up, alerting the player of the added task, and the ability to click on the dungeon, thereby entering it, is removed. Once the player has accessed the task on their mobile app and submitted it, they will be given access to the dungeon. In order to register the submitted task, the player must refresh the display screen by either entering and exiting the pause screen, or leaving the current map slide and returning using the arrow buttons. As of this current build, the only way to gain tasks is by entering certain areas of the map on the web side, such as dungeon entrances, certain areas of the map/dungeons, and shrine locations, however in future development tasks could be added in order to pay for interactions in Tasskian villages and other aspects of the gameplay.</p>
                        </div>
                    </div>